config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  
  resources :gifts
  
  resources :merchants, only: [:show, :index] do
    put :verification
    post :bank_account
    get :payment
    post :payment_stripe
    get :confirmation
  end
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
  }
  
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :customer
  belongs_to :merchant
  before_validation :generate_unique_id, on: :create

  validates :recipient_first_name, presence: true
  validates :recipient_last_name, presence: true
  validates :recipient_email, presence: true
  validates :redeemed, presence: true, on: :update
  validates :unique_id, presence: true
  validates :gift_amount, presence: true
  validate :amount_range?, on: :create
  
  def amount_range? # Could've used :numericality as well...
    if self.gift_amount && !(self.gift_amount >= 5 && self.gift_amount <= 500)
      errors.add(:gift_amount, "Make sure your gift amount is between $5 to $500")
    end
  end
  
  def generate_unique_id
    loop do
      self.unique_id = SecureRandom.base64(64)
      break unless Gift.find_by(unique_id: unique_id)
    end
  end
  
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @gifts = current_user.gifts
  end

  def show
    @gift = Gift.find(params[:id])
  end

  def new
    @gift = Gift.new
  end

  def edit
    @gift = Gift.find(params[:id])
  end
  
  def payment
    @merchant = Merchant.find(params[:merchant_id])
  end

  def create
    @gift = Gift.new(gift_params)
    # merchant = Merchant.find(gift_params[:merchant_id])
    @gift.customer = current_user.customer
    respond_to do |format|
      if @gift.save
        format.html { redirect_to merchant_payment_path({merchant_id: gift_params[:merchant_id]}), notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gift = Gift.find(params[:id])
    @gift.assign_attributes(gift_params)
    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    def gift_params
      params.require(:gift).permit(:recipient_first_name, :recipient_last_name, :recipient_email, :gift_amount, :message, :unique_id, :merchant_id)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= simple_form_for(gift) do |f| %>

  <%= f.input :recipient_first_name, autofocus: true, placeholder: 'Enter recipient first name...', error: "Recipient first name is mandatory" %>
  <%= f.input :recipient_last_name, placeholder: 'Enter recipient last name...', error: "Recipient last name is mandatory" %>
  <%= f.input :recipient_email, placeholder: 'Enter recipient email...', error: "Recipient email is mandatory" %>
  <%= f.input :message, placeholder: 'Enter your message here...' %>
  <%= f.input :gift_amount, placeholder: 'The gift amount has to be between $5 - $500', error: "Oops, make sure you input a number between 5 to 500" %>
  <%= f.hidden_field :merchant_id, value: merchant.id %>
  <%= f.button :submit, 'Create', class: 'btn btn-primary' %>
  
<% end %>
<br />

<form action="" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_kGoomE9QGWg7NTTosdKNUD22"
    data-amount="2000"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-image="/128x128.png"
    data-locale="auto">
  </script>
</form>

<%= link_to 'Cancel', root_path %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gifts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<div class="container">
  <h1>Create Your Gift!</h1>
  <%= render partial: 'form', locals: {gift: @gift} %>
</div>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>