config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  
  resources :gifts
  
  resources :merchants, only: [:show, :index] do
    put :verification
    post :bank_account
    get :payment
    post :payment_stripe
    get :confirmation
  end
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
  }
  
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  require "stripe"
  belongs_to :user
  has_many :gifts, dependent: :destroy
  before_validation :stripe_create, on: :create
  
  ZIPCODE_REGEX = /\A\d{5}(-\d{4})?\z/
  
  validates :store_name,
    presence: true,
    length: { minimum: 1 }
  
  validates :address,
    presence: true
    
  validates :city,
    presence: true
    
  validates :state,
    presence: true
    
  validates :stripe_id,
    presence: true
    
  validates :zipcode,
    presence: true,
    length: { minimum: 5 },
    format: { with: ZIPCODE_REGEX }
  
  def stripe_create
    Stripe.api_key = ENV['STRIPE_API_KEY']
    
    account = Stripe::Account.create(
      {
        country: "US",
        managed: true
      }
      )
    self.stripe_id = account.id
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
require 'stripe'
Stripe.api_key = ENV['STRIPE_API_KEY']

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
    @account = Stripe::Account.retrieve(@merchant.stripe_id)
    @gift = Gift.new
  end
  
  def verification # What's the best way to do validation on these fields?
    @merchant = Merchant.find(params[:merchant_id]) # custom controller action requires explicit call out of :merchant_id as opposed to just :id
    account = Stripe::Account.retrieve(@merchant.stripe_id)
    account.legal_entity.dob.day = params[:day]
    account.legal_entity.dob.month = params[:month]
    account.legal_entity.dob.year = params[:year]
    account.legal_entity.first_name = params[:first_name]
    account.legal_entity.last_name = params[:last_name]
    account.legal_entity.type = params[:type]
    account.legal_entity.address.line1 = params[:line1]
    account.legal_entity.address.line2 = params[:line2]
    account.legal_entity.address.city = params[:city]
    account.legal_entity.address.state = params[:state]
    account.legal_entity.address.country = params[:country]
    account.legal_entity.address.postal_code = params[:postal_code]
    account.legal_entity.business_name = params[:business_name]
    account.legal_entity.ssn_last_4 = params[:last_four]
    # account.tax_id = params[:ein]
    account.tos_acceptance.date = Time.now.to_i
    account.tos_acceptance.ip = request.remote_ip
    account.save
    redirect_to root_path
  end
  
  def bank_account
    @merchant = Merchant.find(params[:merchant_id])
    account = Stripe::Account.retrieve(@merchant.stripe_id)
    if account.external_account = params[:token]
      account.save
      flash[:notice] = "Your bank account has been successfully saved!"
    else
      flash[:notice] = "Uh oh, something went wrong, please try again."
    end
  end
  
  def payment # Write conditional logic in here later for if user wants to save card
    @merchant = Merchant.find(params[:merchant_id])
  end
  
  def payment_stripe
    merchant = Merchant.find(params[:merchant_id])
    gift = current_user.customer.gifts.last
    amount = ((gift.gift_amount)*100)
    token = params[:token]
    begin
      charge = Stripe::Charge.create(
      :amount =>  amount, # amount has to be in cents
      :currency => "usd",
      :source => token,
      :description => "MyApp | #{merchant.store_name}", #Add name in here later
      :application_fee => (amount*0.1).to_i,
      :destination => merchant.stripe_id
      )
      gift.assign_attributes(charge: charge.id)
      gift.save!(validate: false)
    rescue Stripe::CardError => e
    end
    if charge != nil
      redirect_to merchant_confirmation_path
    else
      flash[:notice] = "Charge unsuccessful"
    end
  end
  
  def confirmation
    @merchant = Merchant.find(params[:merchant_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    def merchant_params
      params.require(:merchant).permit(:merchant_id)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_merchant_show.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  Stripe.setPublishableKey("pk_test_kGoomE9QGWg7NTTosdKNUD22");
</script>
<table>
  <thead>
    <tr>
      <th>Outstanding Requirement</th>
      <th>Status</th>
    </tr>
  </thead>
  
  <tbody>
    <% @account.verification.each do |k, v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @account.verification.fields_needed.empty? || @account.verification.fields_needed.include?("external_account") %>
  <p><strong>You've already verified your account!</strong></p>
<% else %>
  <h1>Setup Your Account</h1>
  
  <%= form_tag merchant_verification_path(@merchant), method: :put do %>
    <%# f.error_notification %>
    <p>Date of Birth</p>
    <%= number_field_tag('day', nil, min: 1, max: 31) %>
    <%= number_field_tag('month', nil, min: 1, max: 12) %>
    <%= number_field_tag('year', nil, min: 1914, max: 2016) %>
    
    <p>Owner Full Name</p>
    <%= text_field_tag('first_name', nil, placeholder: 'First Name') %>
    <%= text_field_tag('last_name', nil, placeholder: 'Last Name') %>
    
    <p>Entity Type</p>
    <%= select_tag('type', options_for_select(['individual', 'company'], "individual")) %>
    
    <p>Last 4 Digits of SSN (skip if company)</p>
    <%= text_field_tag('last_four', nil, maxlength: 4, placeholder: '####') %>
    
    <p>Tax EIN (skip if individual)</p>
    <%= text_field_tag('ein', nil, maxlength: 9, placeholder: '###-##-####') %>
    
    <p>Entity Address</p>
    <%= text_field_tag('line1', nil, placeholder: 'Address') %>
    <%= text_field_tag('line2', nil, placeholder: 'Suite Number') %>
    <%= text_field_tag('city', nil, placeholder: 'City') %>
    <%= text_field_tag('state', nil, placeholder: 'State') %>
    <%= text_field_tag('country', nil, placeholder: 'Country') %>
    <%= text_field_tag('postal_code', nil, placeholder: 'Zip Code') %>
    
    <p>Entity Name</p>
    <%= text_field_tag('business_name', nil, placeholder: 'Enter Business Name') %>
  
    <div class="form-actions">
      <%= submit_tag "Verify", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>


<% if @account.verification.fields_needed.include?("external_account") %>
  <h1>Enter your Bank Account Information</h1>
  
  <p>Routing Number</p>
  <%= text_field_tag('routing-number', nil, maxlength: 9, class: 'routing-number') %>
  
  <p>Account Number</p>
  <%= text_field_tag('account-number', nil, maxlength: 13, class: 'account-number') %>
  
  <div class="form-actions">
    <%= link_to 'Submit', '#', id: 'create-token', class: 'btn btn-primary' %>
  </div>
<% else %>
  <h1>Update & Replace Your Existing Bank Account</h1>

  <p>Routing Number</p>
  <%= text_field_tag('routing-number', nil, maxlength: 9, class: 'routing-number') %>
  
  <p>Account Number</p>
  <%= text_field_tag('account-number', nil, maxlength: 13, class: 'account-number') %>
  
  <div class="form-actions">
    <%= link_to 'Submit', '#', id: 'create-token', class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
$(document).ready(function(){
  $('#create-token').on('click', function(){

    Stripe.bankAccount.createToken({
      country: $('.country').val() || "US",
      currency: $('.currency').val() || "USD",
      routing_number: $('.routing-number').val(),
      account_number: $('.account-number').val(),
    }, stripeResponseHandler); 
  });
  
  function stripeResponseHandler(status, response) {
    console.log(status);
    console.log(response);
    $('#example').val(response.id);
    $('#trigger').submit();
  }
});
</script>

<%= form_tag merchant_bank_account_path(@merchant), method: :post, id: 'trigger' do %>
  <%= hidden_field_tag('token', nil, id: 'example') %>
<% end %>

app/views/merchants/confirmation.html.erb
<div class="container">
<h1>Thank You For Your Purchase!</h1>

<%= Stripe::Charge.all %>
</div>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Merchants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/payment.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  Stripe.setPublishableKey("pk_test_kGoomE9QGWg7NTTosdKNUD22");
</script>

<h1>Enter Your Payment Information</h1>

<p>Enter Card Number</p>
<%= text_field_tag('card_num', nil, class: 'card-number', maxlength: 16) %>
<p>Enter Security Code (CVC)</p>
<%= text_field_tag('card_cvc', nil, class: 'card-cvc', maxlength: 3) %>
<p>Enter Expiration Month</p>
<%= number_field_tag('card_exp_month', nil, class: 'card-expiry-month', min: 1, max: 12) %>
<p>Enter Expiration Year</p>
<%= number_field_tag('card_exp_year', nil, class: 'card-expiry-year', min: 2016, max: 2025) %>

<div class="form-actions">
  <%= link_to "Submit Order", "#", id: 'create-token', class: 'btn btn-primary' %> 
</div>


<script>
$(document).ready(function(){
  $('#create-token').on('click', function(){
    
    Stripe.card.createToken({
      number: $('.card-number').val(),
      cvc: $('.card-cvc').val(),
      exp_month: $('.card-expiry-month').val(),
      exp_year: $('.card-expiry-year').val()
    }, stripeResponseHandler);
  });
  
  function stripeResponseHandler(status, response) {
    console.log(status);
    console.log(response);
    $('#response').val(response.id);
    $('#trigger').submit();
  }
});
</script>

<%= form_tag merchant_payment_stripe_path(@merchant), method: :post, id: 'trigger' do %>
  <% hidden_field_tag('token', nil, id: 'response') %>
<% end %>

app/views/merchants/show.html.erb
<div class="container">
<% if current_user.customer %>
  <h1><%= @merchant.store_name %></h1>
  <%= render partial: 'gifts/form', locals: {gift: @gift, merchant: @merchant} %>
  <%= link_to 'Back', merchants_path %>
<% else %>
  <%= render 'merchant_show', locals: {account: @account} %>
<% end %>
</div>